### ISSUE TITLE
Node 17+, `ERR_OSSL_EVP_UNSUPPORTED`, `export NODE_OPTIONS=--openssl-legacy-provider`

### ISSUE THREAD

**Issue by skyl** [zingolabs/zecwallet-lite#35]
dev branch @ 1cdeb615d58b907ebaacbb37aca17ed09f0ebbd7

```
   Compiling tower v0.4.12
   Compiling tiny-bip39 v0.8.2
   Compiling hyper v0.14.18
   Compiling tonic v0.4.3
   Compiling zecwallet-lite v0.1.0 (/workspaces/free2z/zingolabs/zecwallet-lite/native)
    Finished release [optimized] target(s) in 29m 48s
Creating an optimized production build...
/workspaces/free2z/zingolabs/zecwallet-lite/scripts/build.js:11
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/workspaces/free2z/zingolabs/zecwallet-lite/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/workspaces/free2z/zingolabs/zecwallet-lite/node_modules/webpack/lib/NormalModule.js:417:16)
    at /workspaces/free2z/zingolabs/zecwallet-lite/node_modules/webpack/lib/NormalModule.js:452:10
    at /workspaces/free2z/zingolabs/zecwallet-lite/node_modules/webpack/lib/NormalModule.js:323:13
    at /workspaces/free2z/zingolabs/zecwallet-lite/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /workspaces/free2z/zingolabs/zecwallet-lite/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/workspaces/free2z/zingolabs/zecwallet-lite/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /workspaces/free2z/zingolabs/zecwallet-lite/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.2.0
```

It seems that this can be avoided by using:

```
export NODE_OPTIONS=--openssl-legacy-provider
```

**Comment by AloeareV** [comment]
Also on node version `18.2.0`, I'm not getting this error locally. I'll look into this.

**Comment by juanky201271** [comment]
@skyl I think the best strategy for now is to be on node version 16.15.1. What do you think?

**Comment by skyl** [comment]
I think from scratch with 16.15.1 I don't get this anymore. I'll reopen if I find otherwise.
